### ISSUE TITLE
computeFirstOrderConf.m L14: Unclear division

### ISSUE THREAD

**Issue by mar-wir** [smfleming/Self-evaluation-paper#1]
Dear Dr. Fleming,

I have a question regarding a division you compute in the code for the paper "Self-Evaluation of Decision-Making: A General Bayesian Framework for Metacognitive Computation", in the file "computeFirstOrderConf.m", line 14, see following link:

https://github.com/smfleming/Self-evaluation-paper/blob/875dc1b2d14edd360acdc4a7a013d79837bfb139/computeFirstOrderConf.m#L14

You divide the pdf for the sampled "xconf" by its own value. What is the purpose of this division? It would result always in 1 .

Would this not make more sense?:

"conf = normpdf(xconf,dhat(1),sigma_conf)./(normpdf(xconf,dhat(2),sigma_conf) + normpdf(xconf,dhat(1),sigma_conf));"

I am not very familiar with SDT, so if this is a very trivial question, I apologise in advance. Thanks for the help!

Kind Regards,

**Comment by smfleming** [comment]
Hi Marco,

As far as I can tell your line is identical to mine (there's an open bracket before the normpdf) - the difference is that dhat(2) and dhat(1) are reversed in order. The division is by the sum over dhats (the normalisation term).

Best wishes
Steve

**Comment by mar-wir** [comment]
Dear Steve,

I see! It is indeed is clear now. This is when one skims a bit too fast over the code. Many thanks!

All the Best,

Marco
